# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  general

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  registerUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: register-user/index.registerUserHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Handles user registration with MySQL database
      CodeUri: src/handlers/
      Environment:
        Variables:
          MYSQL_HOST: tornymysql.mysql.database.azure.com
          MYSQL_PORT: 3306
          MYSQL_USER: tornymysql
          MYSQL_PASSWORD: Robots4ever1!
          MYSQL_DATABASE: torny_db
      Events:
        Api:
          Type: Api
          Properties:
            Path: /register
            Method: POST

  loginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: login-user/index.loginUserHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Handles user login and JWT token generation
      CodeUri: src/handlers/
      Environment:
        Variables:
          MYSQL_HOST: tornymysql.mysql.database.azure.com
          MYSQL_PORT: 3306
          MYSQL_USER: tornymysql
          MYSQL_PASSWORD: Robots4ever1!
          MYSQL_DATABASE: torny_db
          JWT_SECRET: your-secret-key-here
      Events:
        Api:
          Type: Api
          Properties:
            Path: /login
            Method: POST

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
        
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup

  getTournamentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-tournaments/index.getTournamentsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Handles fetching and filtering tournaments
      CodeUri: src/handlers
      Environment:
        Variables:
          MYSQL_HOST: tornymysql.mysql.database.azure.com
          MYSQL_PORT: 3306
          MYSQL_USER: tornymysql
          MYSQL_PASSWORD: Robots4ever1!
          MYSQL_DATABASE: torny_db
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tournaments
            Method: GET

  getTournamentByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-tournament-by-id/index.getTournamentByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Handles fetching a single tournament with detailed organizer information
      CodeUri: src/handlers
      Environment:
        Variables:
          MYSQL_HOST: tornymysql.mysql.database.azure.com
          MYSQL_PORT: 3306
          MYSQL_USER: tornymysql
          MYSQL_PASSWORD: Robots4ever1!
          MYSQL_DATABASE: torny_db
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tournaments/{id}
            Method: GET

  createTeamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-team/index.createTeamHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Creates a new team and adds the creator as first member
      CodeUri: src/handlers
      Environment:
        Variables:
          MYSQL_HOST: tornymysql.mysql.database.azure.com
          MYSQL_PORT: 3306
          MYSQL_USER: tornymysql
          MYSQL_PASSWORD: Robots4ever1!
          MYSQL_DATABASE: torny_db
      Events:
        Api:
          Type: Api
          Properties:
            Path: /teams
            Method: POST

  getTeamsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-teams/index.getTeamsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get all teams with optional filters
      CodeUri: src/handlers
      Environment:
        Variables:
          MYSQL_HOST: tornymysql.mysql.database.azure.com
          MYSQL_PORT: 3306
          MYSQL_USER: tornymysql
          MYSQL_PASSWORD: Robots4ever1!
          MYSQL_DATABASE: torny_db
      Events:
        Api:
          Type: Api
          Properties:
            Path: /teams
            Method: GET

  getPlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-players/index.getPlayersHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get all players from the database
      CodeUri: src/handlers
      Environment:
        Variables:
          MYSQL_HOST: tornymysql.mysql.database.azure.com
          MYSQL_PORT: 3306
          MYSQL_USER: tornymysql
          MYSQL_PASSWORD: Robots4ever1!
          MYSQL_DATABASE: torny_db
      Events:
        Api:
          Type: Api
          Properties:
            Path: /players
            Method: GET

  getSportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-sports/index.getSportsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get all sports from the database
      CodeUri: src/handlers
      Environment:
        Variables:
          MYSQL_HOST: tornymysql.mysql.database.azure.com
          MYSQL_PORT: 3306
          MYSQL_USER: tornymysql
          MYSQL_PASSWORD: Robots4ever1!
          MYSQL_DATABASE: torny_db
      Events:
        Api:
          Type: Api
          Properties:
            Path: /sports
            Method: GET

Outputs:
  RegisterEndpoint:
    Description: API Gateway endpoint URL for Register function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register"
  
  LoginEndpoint:
    Description: API Gateway endpoint URL for Login function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login"
    
  GetTeamsEndpoint:
    Description: API Gateway endpoint URL for Get Teams function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/teams"
    
  CreateTeamEndpoint:
    Description: API Gateway endpoint URL for Create Team function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/teams"
    
  GetSportsEndpoint:
    Description: API Gateway endpoint URL for Get Sports function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sports"
    
  GetPlayersEndpoint:
    Description: API Gateway endpoint URL for Get Players function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/players"
    
  GetTournamentsEndpoint:
    Description: API Gateway endpoint URL for Get Tournaments function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tournaments"
    
  GetTournamentByIdEndpoint:
    Description: API Gateway endpoint URL for Get Tournament By Id function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tournaments/{id}"
